
control: 
    trivial:
    #   run: {steps: 500_000}
    #   tasks: [
    #     ball_in_cup:catch,
    #     cartpole:balance,
    #     cartpole:balance_sparse,
    #     cartpole:swingup,
    #     reacher:easy,
    #     walker:stand,
    #     walker:walk
    #   ]

    # easy:
    #   run: {steps: 1_000_000}
    #   tasks: [
    #     cartpole:swingup_sparse,
    #     finger:turn_easy,
    #     hopper:stand,
    #     pendulum:swingup,
    #     point_mass:easy,
    #     reacher:hard,
    #     swimmer:swimmer6
    #   ]
    
    # medium:
    #   run: {steps: 2_000_000}
    #   tasks: [
    #     cheetah:run,
    #     finger:spin,
    #     finger:turn_hard,
    #     fish:swim,
    #     fish:upright,
    #     swimmer:swimmer15,
    #     walker:run
    #   ]
    
    hard:
      run: {steps: 5_000_000}
      tasks: [
        # acrobot:swingup,
        # acrobot:swingup_sparse,
        # hopper:hop,
        # humanoid:run,
        # humanoid:stand,
        # humanoid:walk,
        manipulator:bring_ball
      ]


# atari:
#   atari100k: {}
#   atari51: {}
#   atari57: {}